source 'https://github.com/CocoaPods/Specs.git'

target 'EVTTabPageScrollView_Example' do
    pod 'Masonry', '~> 1.1.0'
  pod "EVTTabPageScrollView", :path => "../"
end

target 'EVTTabPageScrollView_Tests' do
  pod "EVTTabPageScrollView", :path => "../"

  
end
